# Setup
gpus: [0]

# Datasets
data_paths: 
   taskonomy: /datasets/taskonomy
   replica: /scratch/ainaz/replica-taskonomized
   gso: /scratch/ainaz/replica-google-objects
   hypersim: /scratch/ainaz/hypersim-dataset2/evermotion/scenes
   blendedMVS: /scratch/ainaz/BlendedMVS/mvs_low_res_taskonomized
   hm3d: /scratch/ainaz/habitat2/

train_datasets:
   taskonomy: True
   replica: True
   gso: True
   hypersim: True
   blendedMVS: True
   hm3d: False

val_datasets:
   taskonomy: True
   replica: True
   gso: True
   hypersim: True
   blendedMVS: True
   hm3d: False

taskonomy_variant: fullplus # tiny, medium, full, fullplus

# DataLoader
batch_size: 8
image_size: 384
num_workers: 16
normalize_rgb: True
normalization_mean: [0.5,0.5,0.5]
normalization_std: [0.5,0.5,0.5]

# Optimizer
lr: 1.0e-5
weight_decay: 2.0e-6

# Model
pretrained: False
pretrained_weights_path: null

# Loggin and Checkpoints
save_dir: /scratch/ainaz/temporary/omnidata-tools/logs # directory to save model checkpoints and logging images
save_top_k: 3         # top models to save checkpoints
num_val_images: 10         # number of validation images to log from each validation dataset
log_step: 3000    # number of steps between image logs